package bus_Booking;

import javax.servlet.http.HttpServlet;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@SuppressWarnings("serial")
@WebServlet("/Bankdetails")
public class Bankreg extends HttpServlet {

	public void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		Connection con = connection.dataBaseConnectionMethod();

		PrintWriter pw = response.getWriter();
		String name = request.getParameter("name");
		String pword = request.getParameter("pword");
		String mail = request.getParameter("mail");
		String pnum = request.getParameter("pnum");
		double amount = Double.valueOf(request.getParameter("amount"));
		String type = request.getParameter("Atype");
// create table userwallet1(acount_no NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITh 1000 increment by 1,user_name varchar2(30)
//		,password varchar2(20),mail_id varchar2(30),phone_no varchar2(10),balance_amount number(12,2),
//		acount_type varchar2(10),primary key(acount_no));
		try {

			PreparedStatement ps1 = con.prepareStatement(
					"insert into userwallet1(user_name,password,mail_id,phone_no,balance_amount,acount_type) values(?,?,?,?,?,?)");
			HttpSession session = request.getSession();
			ps1.setString(1, name);
			ps1.setString(2, pword);
			ps1.setString(3, mail);
			ps1.setString(4, pnum);
			ps1.setDouble(5, amount);
			ps1.setString(6, type);
			int total = ps1.executeUpdate();
			if (total > 0) {
				PreparedStatement ps2 = con
						.prepareStatement("select * from userwallet1 where user_name=? and password=?");
				ps2.setString(1, name);
				ps2.setString(2, pword);

				ResultSet rs = ps2.executeQuery();
				if (rs.next()) {
					int acount = rs.getInt(1);
					request.setAttribute("acno", acount);
					request.setAttribute("confirm", "ok");
					RequestDispatcher rd2 = request.getRequestDispatcher("Bankdtls.jsp");
					rd2.forward(request, response);

				} else {
					pw.println("<html><head></head>");
					pw.println("<body><script>alert('generating of user acount number is fail')</script></body>");
					RequestDispatcher rd3 = request.getRequestDispatcher("Bankdtls.jsp");
					rd3.include(request, response);
					pw.println("</html>");
				}
			} else {
				pw.println("<html><head></head>");
				pw.println("<body><script>alert('inserting user details in bank acount is fail')</script></body>");
				RequestDispatcher rd3 = request.getRequestDispatcher("Bankdtls.jsp");
				rd3.include(request, response);
				pw.println("</html>");
			}

		} catch (SQLException e) {
//			e.printStackTrace();
			pw.println("<html><head></head>");
			pw.println("<body><script>alert('This phone number is already Existed ')</script></body>");
			RequestDispatcher rd3 = request.getRequestDispatcher("Bankdtls.jsp");
			rd3.include(request, response);
			pw.println("</html>");

		}

	}
}
